### ISSUE TITLE
Compatibilité V4

### ISSUE THREAD

**Issue by Xavoo** [jmz84/plugin-digicode#6]
Bonjour ! 

Je découvre ce plugin, et après plusieurs heures à comprendre pourquoi la roue de configuration n'apparaissait jamais, j'ai trouvé sur le forum JEEDOM qu'une compatibilité avec la V4 n'était pas tout à fait travaillée. 

Je constate dans les pull requests que tout le travail de modification semble fait, est il possible de pousser une mise à jour vers jeedom ?  :) 

Merci beaucoup !

**Comment by MrJuju0319** [comment]
Bonjour @Xavoo  j'ai mis a jours le plugins car il ne bouge pas, je te donne les fichier tu as juste a pousser le dossier dans les fichier de jeedom/plugin

PS : 
[digicode.zip](https://github.com/jmz84/plugin-digicode/files/4016877/digicode.zip)

**Comment by MrJuju0319** [comment]
Edit: 
[digicode.zip](https://github.com/jmz84/plugin-digicode/files/4049709/digicode.zip)

**Comment by jmz84** [comment]
Bonjour à tous, 
le plugin vient d'être mis à jour.
